#!/bin/bash

export PENNYLANE_ROOT="${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}"
export PYTHON_VENV_DIR=$PENNYLANE_ROOT/venvs
export CPU_VENV=$PYTHON_VENV_DIR/cpu
export GPU_VENV=$PYTHON_VENV_DIR/gpu
export AER_MPI_VENV=$PYTHON_VENV_DIR/aer_mpi
export BENCHMARK_RUN_ID=11-09-2023

mkdir -p $PYTHON_VENV_DIR
